// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://advromlqmbjgpiusejvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkdnJvbWxxbWJqZ3BpdXNlanZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MjQzNjUsImV4cCI6MjA2NjIwMDM2NX0.98QlxrIGoWDMuhk4kWkshgDsYL9CVzWqtlm89wwhkVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);