
import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { useLanguage } from "@/contexts/LanguageContext";
import { BarChart3, Download, FileText, TrendingUp, Calendar, Filter, Printer } from 'lucide-react';
import { ViewReportDialog } from './ViewReportDialog';

export function ReportingCenter() {
  const [reportType, setReportType] = useState('');
  const [timePeriod, setTimePeriod] = useState('');
  const [format, setFormat] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedReport, setSelectedReport] = useState<any>(null);
  const [viewDialogOpen, setViewDialogOpen] = useState(false);
  const [newReportDialogOpen, setNewReportDialogOpen] = useState(false);
  const { toast } = useToast();
  const { t, language, dir } = useLanguage();

  const reports = [
    {
      id: 'RPT-001',
      title: t('comprehensiveComplianceReport'),
      description: t('comprehensiveComplianceDesc'),
      type: t('periodicReport'),
      frequency: t('monthly'),
      lastGenerated: '2024-06-01',
      format: 'PDF',
      status: t('ready')
    },
    {
      id: 'RPT-002',
      title: t('controlsMatrixReport'),
      description: t('controlsMatrixDesc'),
      type: t('operationalReport'),
      frequency: t('weekly'),
      lastGenerated: '2024-06-15',
      format: 'Excel',
      status: t('updating')
    },
    {
      id: 'RPT-003',
      title: t('expiredPoliciesReport'),
      description: t('expiredPoliciesDesc'),
      type: t('exceptionalReport'),
      frequency: t('asNeeded'),
      lastGenerated: '2024-06-10',
      format: 'PDF',
      status: t('ready')
    },
    {
      id: 'RPT-004',
      title: t('auditPerformanceReport'),
      description: t('auditPerformanceDesc'),
      type: t('performanceReport'),
      frequency: t('quarterly'),
      lastGenerated: '2024-03-31',
      format: 'PowerPoint',
      status: t('requiresUpdate')
    }
  ];

  const handleGenerateReport = async () => {
    if (!reportType || !timePeriod || !format) {
      toast({
        title: t('error'),
        description: language === 'ar' ? "يرجى اختيار جميع الحقول المطلوبة" : "Please select all required fields",
        variant: "destructive"
      });
      return;
    }

    setIsGenerating(true);
    
    // Simulate report generation
    setTimeout(() => {
      setIsGenerating(false);
      setNewReportDialogOpen(false);
      toast({
        title: t('success'),
        description: language === 'ar' ? 
          `تم إنشاء ${reportType} للفترة ${timePeriod} بتنسيق ${format}` :
          `Generated ${reportType} for ${timePeriod} in ${format} format`,
      });
      
      // Simulate download
      const blob = new Blob(['Sample report content'], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `report_${Date.now()}.${format.toLowerCase()}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 2000);
  };

  const handleOpenNewReport = () => {
    setNewReportDialogOpen(true);
  };

  const handleViewReport = (report: any) => {
    setSelectedReport(report);
    setViewDialogOpen(true);
  };

  const handleDownloadReport = (report: any) => {
    toast({
      title: t('downloading'),
      description: language === 'ar' ? `جاري تحميل ${report.title}` : `Downloading ${report.title}`,
    });
    
    // Create more comprehensive report content
    const reportContent = `
${report.title}
${'-'.repeat(50)}

Report ID: ${report.id}
Type: ${report.type}
Frequency: ${report.frequency}
Last Generated: ${report.lastGenerated}
Status: ${report.status}

Description:
${report.description}

${'-'.repeat(50)}
Report Content:

This report contains detailed compliance information including:
- Control assessments and status
- Policy compliance metrics
- Audit findings and recommendations
- Risk analysis and mitigation strategies
- Performance indicators and trends

Generated by Arab Compliance Hub
${new Date().toLocaleDateString()}
    `;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.id}_${report.title.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrintReport = (report: any) => {
    toast({
      title: t('printing'),
      description: language === 'ar' ? `جاري إعداد ${report.title} للطباعة` : `${t('preparingForPrint')} ${report.title}`,
    });
    
    // Create print content
    const printContent = `
      <html>
        <head>
          <title>${report.title}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #1e40af; }
            .header { border-bottom: 2px solid #1e40af; padding-bottom: 10px; margin-bottom: 20px; }
            .content { line-height: 1.6; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${report.title}</h1>
            <p>${t('reportNumber')}: ${report.id}</p>
            <p>${t('lastGenerated')}: ${report.lastGenerated}</p>
          </div>
          <div class="content">
            <p>${report.description}</p>
            <p>${t('type')}: ${report.type}</p>
            <p>${t('frequency')}: ${report.frequency}</p>
            <p>${t('status')}: ${report.status}</p>
          </div>
        </body>
      </html>
    `;
    
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 250);
    }
  };

  const getStatusBadge = (status: string) => {
    const variants = {
      [t('ready')]: 'bg-green-100 text-green-800',
      [t('updating')]: 'bg-yellow-100 text-yellow-800',
      [t('requiresUpdate')]: 'bg-red-100 text-red-800'
    };
    
    return (
      <Badge className={`${variants[status as keyof typeof variants]} text-xs`}>
        {status}
      </Badge>
    );
  };

  const getFormatBadge = (format: string) => {
    const variants = {
      'PDF': 'bg-red-100 text-red-800',
      'Excel': 'bg-green-100 text-green-800',
      'PowerPoint': 'bg-blue-100 text-blue-800'
    };
    
    return (
      <Badge variant="outline" className={`${variants[format as keyof typeof variants]} text-xs`}>
        {format}
      </Badge>
    );
  };

  return (
    <div className="space-y-6" dir={dir}>
      <div className={`flex items-center justify-between ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
        <div className={language === 'ar' ? 'text-right' : 'text-left'}>
          <h2 className="text-3xl font-bold text-gray-900">{t('reportingCenterTitle')}</h2>
          <p className="text-gray-600 mt-1">{t('reportingCenterDesc')}</p>
        </div>
        <div className={`flex gap-3 ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
          <Button variant="outline" className={`gap-2 ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
            <Filter className="h-4 w-4" />
            {t('filter')}
          </Button>
          <Button
            className={`gap-2 bg-blue-600 hover:bg-blue-700 ${language === 'ar' ? 'flex-row-reverse' : ''}`}
            onClick={handleOpenNewReport}
          >
            <FileText className="h-4 w-4" />
            {t('newReport')}
          </Button>
        </div>
      </div>

      {/* Report Generation */}
      <Card>
        <CardHeader>
          <CardTitle className={`flex items-center gap-2 ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
            <BarChart3 className="h-5 w-5 text-blue-600" />
            {t('quickReportGenerator')}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <Select value={reportType} onValueChange={setReportType}>
              <SelectTrigger>
                <SelectValue placeholder={t('reportType')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={t('complianceReport')}>{t('complianceReport')}</SelectItem>
                <SelectItem value={t('controlsMatrix')}>{t('controlsMatrix')}</SelectItem>
                <SelectItem value={t('policies')}>{t('policies')}</SelectItem>
                <SelectItem value={t('audit')}>{t('audit')}</SelectItem>
              </SelectContent>
            </Select>
            
            <Select value={timePeriod} onValueChange={setTimePeriod}>
              <SelectTrigger>
                <SelectValue placeholder={t('timePeriod')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={t('lastWeek')}>{t('lastWeek')}</SelectItem>
                <SelectItem value={t('lastMonth')}>{t('lastMonth')}</SelectItem>
                <SelectItem value={t('lastQuarter')}>{t('lastQuarter')}</SelectItem>
                <SelectItem value={t('lastYear')}>{t('lastYear')}</SelectItem>
              </SelectContent>
            </Select>
            
            <Select value={format} onValueChange={setFormat}>
              <SelectTrigger>
                <SelectValue placeholder={t('format')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="PDF">PDF</SelectItem>
                <SelectItem value="Excel">Excel</SelectItem>
                <SelectItem value="PowerPoint">PowerPoint</SelectItem>
              </SelectContent>
            </Select>
            
            <Button 
              className={`w-full gap-2 ${language === 'ar' ? 'flex-row-reverse' : ''}`}
              onClick={handleGenerateReport}
              disabled={isGenerating}
            >
              <Download className="h-4 w-4" />
              {isGenerating ? t('generating') : t('generateReport')}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {reports.map((report) => (
          <Card key={report.id} className="hover:shadow-md transition-shadow">
            <CardHeader className="pb-3">
              <div className={`flex items-start justify-between ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
                <div className={language === 'ar' ? 'text-right' : 'text-left'}>
                  <CardTitle className="text-lg">{report.title}</CardTitle>
                  <p className="text-sm text-gray-500 mt-1">{report.description}</p>
                </div>
                <FileText className="h-5 w-5 text-blue-600 flex-shrink-0" />
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className={`flex items-center justify-between ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
                <span className="text-sm text-gray-600">{t('reportNumber')}:</span>
                <Badge variant="outline">{report.id}</Badge>
              </div>
              
              <div className={`flex items-center justify-between ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
                <span className="text-sm text-gray-600">{t('type')}:</span>
                <span className="text-sm font-medium">{report.type}</span>
              </div>

              <div className={`flex items-center justify-between ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
                <span className="text-sm text-gray-600">{t('frequency')}:</span>
                <span className="text-sm font-medium">{report.frequency}</span>
              </div>

              <div className={`flex items-center justify-between ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
                <span className="text-sm text-gray-600">{t('lastGenerated')}:</span>
                <span className="text-sm font-medium">{report.lastGenerated}</span>
              </div>

              <div className={`flex items-center justify-between ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
                <span className="text-sm text-gray-600">{t('format')}:</span>
                {getFormatBadge(report.format)}
              </div>

              <div className={`flex items-center justify-between ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
                <span className="text-sm text-gray-600">{t('status')}:</span>
                {getStatusBadge(report.status)}
              </div>

              <div className={`flex gap-2 pt-2 ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
                <Button 
                  size="sm" 
                  variant="outline" 
                  className={`flex-1 gap-2 ${language === 'ar' ? 'flex-row-reverse' : ''}`}
                  onClick={() => handleViewReport(report)}
                >
                  <FileText className="h-4 w-4" />
                  {t('view')}
                </Button>
                <Button 
                  size="sm" 
                  variant="outline" 
                  className={`flex-1 gap-2 ${language === 'ar' ? 'flex-row-reverse' : ''}`}
                  onClick={() => handleDownloadReport(report)}
                >
                  <Download className="h-4 w-4" />
                  {t('download')}
                </Button>
                <Button 
                  size="sm" 
                  variant="outline" 
                  className={`flex-1 gap-2 ${language === 'ar' ? 'flex-row-reverse' : ''}`}
                  onClick={() => handlePrintReport(report)}
                >
                  <Printer className="h-4 w-4" />
                  {language === 'ar' ? 'طباعة' : 'Print'}
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Analytics Dashboard */}
      <Card>
        <CardHeader>
          <CardTitle className={`flex items-center gap-2 ${language === 'ar' ? 'flex-row-reverse' : ''}`}>
            <TrendingUp className="h-5 w-5 text-blue-600" />
            {t('analyticsPanel')}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center p-4 bg-blue-50 rounded-lg">
              <div className="text-3xl font-bold text-blue-900 mb-2">47</div>
              <div className="text-sm text-blue-600">{t('reportsGeneratedThisMonth')}</div>
              <div className="text-xs text-blue-500 mt-1">+12% {t('fromLastMonth')}</div>
            </div>
            <div className="text-center p-4 bg-green-50 rounded-lg">
              <div className="text-3xl font-bold text-green-900 mb-2">93%</div>
              <div className="text-sm text-green-600">{t('reportAccuracyRate')}</div>
              <div className="text-xs text-green-500 mt-1">+2% {t('fromLastMonth')}</div>
            </div>
            <div className="text-center p-4 bg-yellow-50 rounded-lg">
              <div className="text-3xl font-bold text-yellow-900 mb-2">2.3</div>
              <div className="text-sm text-yellow-600">{t('averageGenerationTime')}</div>
              <div className="text-xs text-yellow-500 mt-1">-15% {t('fromLastMonth')}</div>
            </div>
          </div>
        </CardContent>
      </Card>

      <ViewReportDialog
        report={selectedReport}
        open={viewDialogOpen}
        onOpenChange={setViewDialogOpen}
        onDownload={handleDownloadReport}
        onPrint={handlePrintReport}
      />

      <Dialog open={newReportDialogOpen} onOpenChange={setNewReportDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>{t('newReport')}</DialogTitle>
          </DialogHeader>

          <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
            <Select value={reportType} onValueChange={setReportType}>
              <SelectTrigger>
                <SelectValue placeholder={t('reportType')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={t('complianceReport')}>{t('complianceReport')}</SelectItem>
                <SelectItem value={t('controlsMatrix')}>{t('controlsMatrix')}</SelectItem>
                <SelectItem value={t('policies')}>{t('policies')}</SelectItem>
                <SelectItem value={t('audit')}>{t('audit')}</SelectItem>
              </SelectContent>
            </Select>

            <Select value={timePeriod} onValueChange={setTimePeriod}>
              <SelectTrigger>
                <SelectValue placeholder={t('timePeriod')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={t('lastWeek')}>{t('lastWeek')}</SelectItem>
                <SelectItem value={t('lastMonth')}>{t('lastMonth')}</SelectItem>
                <SelectItem value={t('lastQuarter')}>{t('lastQuarter')}</SelectItem>
                <SelectItem value={t('lastYear')}>{t('lastYear')}</SelectItem>
              </SelectContent>
            </Select>

            <Select value={format} onValueChange={setFormat}>
              <SelectTrigger>
                <SelectValue placeholder={t('format')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="PDF">PDF</SelectItem>
                <SelectItem value="Excel">Excel</SelectItem>
                <SelectItem value="PowerPoint">PowerPoint</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="flex justify-end">
            <Button onClick={handleGenerateReport} disabled={isGenerating}>
              <Download className="mr-2 h-4 w-4" />
              {isGenerating ? t('generating') : t('generateReport')}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
