-- Recovery script for dependency objects
-- Generated: 04/17/2026 05:53:01


-- SOURCE: C:\Users\Saifuddin\accredicore-main\app-source\supabase\migrations\20250623135003-92677312-1e53-42dd-b4be-bca1f2d72629.sql
CREATE TYPE public.app_role AS ENUM ('system_admin', 'super_user', 'admin', 'user');



-- SOURCE: C:\Users\Saifuddin\accredicore-main\app-source\supabase\migrations\20250915025130_979f3813-b494-46d3-84ec-66e4c2193e44.sql
CREATE TABLE public.teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  name_ar TEXT,
  description TEXT,
  description_ar TEXT,
  department TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);



-- SOURCE: C:\Users\Saifuddin\accredicore-main\app-source\supabase\migrations\20250915025211_1cd0fdf5-cb39-423e-98ca-0b78a98af23d.sql
CREATE TABLE public.teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  name_ar TEXT,
  description TEXT,
  description_ar TEXT,
  department TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);


