-- Phase 3 frontend contract patch for local PostgreSQL
-- Adds the minimum schema and RPC surface used by the frontend.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
  id uuid PRIMARY KEY,
  email text,
  raw_user_meta_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public' AND t.typname = 'app_role'
  ) THEN
    CREATE TYPE public.app_role AS ENUM (
      'system_admin',
      'super_user',
      'admin',
      'developer',
      'user',
      'team',
      'client'
    );
  END IF;
END
$$;

ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'developer';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'team';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'client';

CREATE SCHEMA IF NOT EXISTS auth;

CREATE OR REPLACE FUNCTION auth.uid()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT '00000000-0000-0000-0000-000000000000'::uuid;
$$;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS last_login timestamptz;

ALTER TABLE public.user_roles
  ALTER COLUMN role TYPE public.app_role
  USING role::text::public.app_role;

CREATE TABLE IF NOT EXISTS public.departments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  manager_id uuid REFERENCES public.profiles(id),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.facilities (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  department_id integer REFERENCES public.departments(id) ON DELETE SET NULL,
  location text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_progress (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_id integer NOT NULL REFERENCES public.facilities(id) ON DELETE CASCADE,
  control_id bigint NOT NULL REFERENCES public.controls(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'not_started',
  progress_percentage integer NOT NULL DEFAULT 0,
  notes text,
  due_date timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  evidence_files text[] DEFAULT ARRAY[]::text[],
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (facility_id, control_id)
);

CREATE TABLE IF NOT EXISTS public.audit_schedules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  audit_type text NOT NULL,
  department text NOT NULL,
  scheduled_date date NOT NULL,
  scheduled_time text,
  duration_days integer DEFAULT 1,
  priority text NOT NULL DEFAULT 'medium',
  auditor_name text,
  auditor_company text,
  status text NOT NULL DEFAULT 'scheduled',
  created_by uuid NOT NULL REFERENCES public.profiles(id),
  assigned_to uuid REFERENCES public.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.policies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  content text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT 'general',
  status text NOT NULL DEFAULT 'draft',
  version integer NOT NULL DEFAULT 1,
  created_by uuid NOT NULL REFERENCES public.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.compliance_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  policy_id uuid REFERENCES public.policies(id) ON DELETE SET NULL,
  title text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'pending',
  assigned_to uuid REFERENCES public.profiles(id),
  due_date timestamptz,
  completed_date timestamptz,
  created_by uuid NOT NULL REFERENCES public.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.policy_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  title_ar text,
  description text,
  description_ar text,
  content text NOT NULL DEFAULT '',
  content_ar text,
  category text NOT NULL DEFAULT 'general',
  tags text[] DEFAULT ARRAY[]::text[],
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES public.profiles(id),
  file_path text,
  file_size bigint,
  mime_type text,
  storage_bucket text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  file_path text NOT NULL DEFAULT '',
  storage_bucket text NOT NULL DEFAULT 'documents',
  original_filename text NOT NULL DEFAULT 'document.txt',
  mime_type text NOT NULL DEFAULT 'text/plain',
  category text NOT NULL DEFAULT 'general',
  tags text[] DEFAULT ARRAY[]::text[],
  version integer NOT NULL DEFAULT 1,
  file_size bigint,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid NOT NULL REFERENCES public.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.policy_manual_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  policy_id text NOT NULL,
  policy_title text NOT NULL,
  policy_content text NOT NULL DEFAULT '',
  section text NOT NULL DEFAULT 'Policy Manuals',
  assigned_to uuid REFERENCES public.profiles(id),
  assigned_by uuid NOT NULL REFERENCES public.profiles(id),
  status text NOT NULL DEFAULT 'pending',
  priority text NOT NULL DEFAULT 'medium',
  change_notes text,
  task_description text,
  due_date timestamptz,
  completed_at timestamptz,
  file_path text,
  file_size bigint,
  original_filename text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.team_members (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id bigint REFERENCES public.teams(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'member',
  permissions text[] DEFAULT ARRAY[]::text[],
  is_active boolean NOT NULL DEFAULT true,
  joined_at timestamptz DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (team_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.task_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  comment text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.task_progress (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  progress_percentage integer NOT NULL DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.project_quality_plan (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL,
  title text NOT NULL,
  description text,
  details jsonb DEFAULT '{}'::jsonb,
  order_index integer NOT NULL DEFAULT 0,
  team_id bigint REFERENCES public.teams(id) ON DELETE SET NULL,
  created_by uuid REFERENCES public.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.incidents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  priority text NOT NULL DEFAULT 'medium',
  status text NOT NULL DEFAULT 'open',
  created_by uuid NOT NULL REFERENCES public.profiles(id),
  team_id bigint REFERENCES public.teams(id) ON DELETE SET NULL,
  assigned_user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.investigation_notes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id integer NOT NULL REFERENCES public.incidents(id) ON DELETE CASCADE,
  note text NOT NULL,
  author_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.action_plans (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id integer NOT NULL REFERENCES public.incidents(id) ON DELETE CASCADE,
  plan text NOT NULL,
  status text NOT NULL DEFAULT 'proposed',
  proposer_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.root_cause_analyses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  problem text NOT NULL,
  incident_id integer REFERENCES public.incidents(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'draft',
  priority text NOT NULL DEFAULT 'medium',
  team_id bigint REFERENCES public.teams(id) ON DELETE SET NULL,
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  completed_at timestamptz,
  root_causes jsonb DEFAULT '[]'::jsonb,
  contributing_factors jsonb DEFAULT '[]'::jsonb,
  why_analysis jsonb DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.improvement_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  root_cause_id uuid REFERENCES public.root_cause_analyses(id) ON DELETE SET NULL,
  incident_id integer REFERENCES public.incidents(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'proposed',
  priority text NOT NULL DEFAULT 'medium',
  assigned_to uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  team_id bigint REFERENCES public.teams(id) ON DELETE SET NULL,
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  target_completion_date timestamptz,
  actual_completion_date timestamptz,
  action_items jsonb DEFAULT '[]'::jsonb,
  success_metrics jsonb DEFAULT '[]'::jsonb,
  budget_allocated numeric,
  budget_spent numeric,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_current_user_role()
RETURNS public.app_role
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT COALESCE(
    (
      SELECT role
      FROM public.user_roles
      WHERE user_id = auth.uid()
      ORDER BY
        CASE role
          WHEN 'system_admin' THEN 1
          WHEN 'super_user' THEN 2
          WHEN 'admin' THEN 3
          WHEN 'developer' THEN 4
          WHEN 'team' THEN 5
          WHEN 'client' THEN 6
          ELSE 7
        END
      LIMIT 1
    ),
    'user'::public.app_role
  );
$$;

CREATE OR REPLACE FUNCTION public.get_department_compliance_summary(dept_id integer DEFAULT NULL)
RETURNS TABLE (
  department_name text,
  total_controls bigint,
  completed_controls bigint,
  in_progress_controls bigint,
  not_started_controls bigint,
  compliance_percentage numeric
)
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT
    d.name AS department_name,
    COUNT(c.id)::bigint AS total_controls,
    COUNT(*) FILTER (WHERE ap.status = 'completed')::bigint AS completed_controls,
    COUNT(*) FILTER (WHERE ap.status = 'in_progress')::bigint AS in_progress_controls,
    COUNT(*) FILTER (
      WHERE ap.status IS NULL OR ap.status IN ('not_started', 'pending')
    )::bigint AS not_started_controls,
    CASE
      WHEN COUNT(c.id) = 0 THEN 0
      ELSE ROUND(
        (COUNT(*) FILTER (WHERE ap.status = 'completed')::numeric / COUNT(c.id)::numeric) * 100,
        2
      )
    END AS compliance_percentage
  FROM public.departments d
  CROSS JOIN public.controls c
  LEFT JOIN public.facilities f
    ON f.department_id = d.id
   AND f.is_active = true
  LEFT JOIN public.audit_progress ap
    ON ap.facility_id = f.id
   AND ap.control_id = c.id
  WHERE d.is_active = true
    AND (dept_id IS NULL OR d.id = dept_id)
  GROUP BY d.id, d.name
  ORDER BY d.name;
$$;

CREATE OR REPLACE FUNCTION public.update_audit_progress(
  p_facility_id integer,
  p_user_id uuid,
  p_control_id bigint,
  p_status text,
  p_progress_percentage integer,
  p_notes text DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  progress_percentage integer,
  status text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_row public.audit_progress%ROWTYPE;
BEGIN
  INSERT INTO public.audit_progress (
    facility_id,
    user_id,
    control_id,
    status,
    progress_percentage,
    notes,
    completed_at,
    updated_at
  )
  VALUES (
    p_facility_id,
    p_user_id,
    p_control_id,
    p_status,
    p_progress_percentage,
    p_notes,
    CASE WHEN p_status = 'completed' THEN now() ELSE NULL END,
    now()
  )
  ON CONFLICT (facility_id, control_id)
  DO UPDATE SET
    user_id = EXCLUDED.user_id,
    status = EXCLUDED.status,
    progress_percentage = EXCLUDED.progress_percentage,
    notes = EXCLUDED.notes,
    completed_at = CASE
      WHEN EXCLUDED.status = 'completed' THEN now()
      ELSE public.audit_progress.completed_at
    END,
    updated_at = now()
  RETURNING * INTO v_row;

  RETURN QUERY
  SELECT v_row.id, v_row.progress_percentage, v_row.status;
END;
$$;

DROP TRIGGER IF EXISTS update_departments_updated_at ON public.departments;
CREATE TRIGGER update_departments_updated_at
BEFORE UPDATE ON public.departments
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_facilities_updated_at ON public.facilities;
CREATE TRIGGER update_facilities_updated_at
BEFORE UPDATE ON public.facilities
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_audit_schedules_updated_at ON public.audit_schedules;
CREATE TRIGGER update_audit_schedules_updated_at
BEFORE UPDATE ON public.audit_schedules
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_policies_updated_at ON public.policies;
CREATE TRIGGER update_policies_updated_at
BEFORE UPDATE ON public.policies
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_policy_templates_updated_at ON public.policy_templates;
CREATE TRIGGER update_policy_templates_updated_at
BEFORE UPDATE ON public.policy_templates
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_documents_updated_at ON public.documents;
CREATE TRIGGER update_documents_updated_at
BEFORE UPDATE ON public.documents
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_policy_manual_tasks_updated_at ON public.policy_manual_tasks;
CREATE TRIGGER update_policy_manual_tasks_updated_at
BEFORE UPDATE ON public.policy_manual_tasks
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_project_quality_plan_updated_at ON public.project_quality_plan;
CREATE TRIGGER update_project_quality_plan_updated_at
BEFORE UPDATE ON public.project_quality_plan
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_incidents_updated_at ON public.incidents;
CREATE TRIGGER update_incidents_updated_at
BEFORE UPDATE ON public.incidents
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_action_plans_updated_at ON public.action_plans;
CREATE TRIGGER update_action_plans_updated_at
BEFORE UPDATE ON public.action_plans
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_root_cause_analyses_updated_at ON public.root_cause_analyses;
CREATE TRIGGER update_root_cause_analyses_updated_at
BEFORE UPDATE ON public.root_cause_analyses
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_improvement_plans_updated_at ON public.improvement_plans;
CREATE TRIGGER update_improvement_plans_updated_at
BEFORE UPDATE ON public.improvement_plans
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

INSERT INTO auth.users (id, email, raw_user_meta_data)
VALUES (
  '00000000-0000-0000-0000-000000000000'::uuid,
  'local-admin@accredicore.local',
  '{"full_name":"Local Admin"}'::jsonb
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.profiles (id, email, full_name)
VALUES (
  '00000000-0000-0000-0000-000000000000'::uuid,
  'local-admin@accredicore.local',
  'Local Admin'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.user_roles (user_id, role)
VALUES (
  '00000000-0000-0000-0000-000000000000'::uuid,
  'system_admin'::public.app_role
)
ON CONFLICT (user_id, role) DO NOTHING;

INSERT INTO public.departments (name, description)
SELECT 'Quality Management', 'Default local department'
WHERE NOT EXISTS (
  SELECT 1 FROM public.departments WHERE name = 'Quality Management'
);

INSERT INTO public.facilities (name, department_id)
SELECT 'Main Facility', d.id
FROM public.departments d
WHERE d.name = 'Quality Management'
  AND NOT EXISTS (
    SELECT 1 FROM public.facilities WHERE name = 'Main Facility'
  );
