-- Notification and policy attestation patch
-- Adds a local notification workflow and explicit staff acknowledgment records
-- so manual UAT can verify approval routing, distribution, and staff attestation.

CREATE TABLE IF NOT EXISTS public.notification_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  description text
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type_id integer REFERENCES public.notification_types(id) ON DELETE SET NULL,
  message text NOT NULL,
  metadata jsonb,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.notification_preferences (
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type_id integer NOT NULL REFERENCES public.notification_types(id) ON DELETE CASCADE,
  email_enabled boolean DEFAULT true,
  push_enabled boolean DEFAULT true,
  sms_enabled boolean DEFAULT false,
  PRIMARY KEY (user_id, type_id)
);

CREATE TABLE IF NOT EXISTS public.policy_attestations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  policy_id uuid NOT NULL REFERENCES public.policies(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  requested_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending',
  instructions text,
  notes text,
  due_at timestamptz,
  requested_at timestamptz NOT NULL DEFAULT now(),
  acknowledged_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_policy_attestations_pending_unique
  ON public.policy_attestations(policy_id, user_id)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_notifications_user_created
  ON public.notifications(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_policy_attestations_policy
  ON public.policy_attestations(policy_id, requested_at DESC);

INSERT INTO public.notification_types (type_key, display_name, description)
VALUES
  ('policy_approval', 'Policy Approval', 'Approval workflow and stage change notifications'),
  ('policy_attestation', 'Policy Attestation', 'Staff acknowledgment and attestation notifications'),
  ('system', 'System', 'General system notifications')
ON CONFLICT (type_key) DO UPDATE
SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description;

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.policy_attestations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notifications_select_relevant" ON public.notifications;
CREATE POLICY "notifications_select_relevant"
ON public.notifications
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "notifications_update_relevant" ON public.notifications;
CREATE POLICY "notifications_update_relevant"
ON public.notifications
FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "notifications_insert_admin" ON public.notifications;
CREATE POLICY "notifications_insert_admin"
ON public.notifications
FOR INSERT
TO authenticated
WITH CHECK (public.is_elevated_role());

DROP POLICY IF EXISTS "notification_preferences_select_relevant" ON public.notification_preferences;
CREATE POLICY "notification_preferences_select_relevant"
ON public.notification_preferences
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "notification_preferences_manage_relevant" ON public.notification_preferences;
CREATE POLICY "notification_preferences_manage_relevant"
ON public.notification_preferences
FOR ALL
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "policy_attestations_select_relevant" ON public.policy_attestations;
CREATE POLICY "policy_attestations_select_relevant"
ON public.policy_attestations
FOR SELECT
TO authenticated
USING (
  public.is_elevated_role()
  OR user_id = auth.uid()
  OR requested_by = auth.uid()
);

DROP POLICY IF EXISTS "policy_attestations_insert_admin" ON public.policy_attestations;
CREATE POLICY "policy_attestations_insert_admin"
ON public.policy_attestations
FOR INSERT
TO authenticated
WITH CHECK (public.is_elevated_role());

DROP POLICY IF EXISTS "policy_attestations_update_relevant" ON public.policy_attestations;
CREATE POLICY "policy_attestations_update_relevant"
ON public.policy_attestations
FOR UPDATE
TO authenticated
USING (
  public.is_elevated_role()
  OR user_id = auth.uid()
  OR requested_by = auth.uid()
)
WITH CHECK (
  public.is_elevated_role()
  OR user_id = auth.uid()
  OR requested_by = auth.uid()
);

CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_policy_attestations_updated_at ON public.policy_attestations;
CREATE TRIGGER set_policy_attestations_updated_at
BEFORE UPDATE ON public.policy_attestations
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

DROP TRIGGER IF EXISTS audit_notifications_changes ON public.notifications;
CREATE TRIGGER audit_notifications_changes
AFTER INSERT OR UPDATE OR DELETE ON public.notifications
FOR EACH ROW EXECUTE FUNCTION public.audit_row_changes();

DROP TRIGGER IF EXISTS audit_policy_attestations_changes ON public.policy_attestations;
CREATE TRIGGER audit_policy_attestations_changes
AFTER INSERT OR UPDATE OR DELETE ON public.policy_attestations
FOR EACH ROW EXECUTE FUNCTION public.audit_row_changes();

CREATE OR REPLACE FUNCTION public.send_notification(
  p_user_id uuid,
  p_type_key text,
  p_message text,
  p_metadata jsonb DEFAULT NULL,
  p_expires_at timestamptz DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_type_id integer;
  v_notification_id integer;
BEGIN
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'Notification recipient is required';
  END IF;

  SELECT id
  INTO v_type_id
  FROM public.notification_types
  WHERE type_key = COALESCE(p_type_key, 'system');

  IF v_type_id IS NULL THEN
    INSERT INTO public.notification_types(type_key, display_name, description)
    VALUES (
      COALESCE(p_type_key, 'system'),
      initcap(replace(COALESCE(p_type_key, 'system'), '_', ' ')),
      'Auto-created local notification type'
    )
    RETURNING id INTO v_type_id;
  END IF;

  INSERT INTO public.notifications (
    user_id,
    type_id,
    message,
    metadata,
    expires_at
  )
  VALUES (
    p_user_id,
    v_type_id,
    p_message,
    COALESCE(p_metadata, '{}'::jsonb),
    p_expires_at
  )
  RETURNING id INTO v_notification_id;

  RETURN v_notification_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.send_notification(
  p_message text,
  p_type_name text,
  p_user_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM public.send_notification(
    p_user_id,
    COALESCE(NULLIF(trim(p_type_name), ''), 'system'),
    p_message,
    NULL,
    NULL
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.send_notification()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN;
END;
$$;

CREATE OR REPLACE FUNCTION public.notify_users_by_role(
  p_role public.app_role,
  p_type_key text,
  p_message text,
  p_metadata jsonb DEFAULT NULL,
  p_expires_at timestamptz DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_count integer := 0;
  v_user_id uuid;
BEGIN
  FOR v_user_id IN
    SELECT DISTINCT user_roles.user_id
    FROM public.user_roles
    WHERE user_roles.role = p_role
  LOOP
    PERFORM public.send_notification(
      v_user_id,
      p_type_key,
      p_message,
      p_metadata,
      p_expires_at
    );
    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_notification_read(p_notification_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.notifications
  SET is_read = true
  WHERE id = p_notification_id
    AND user_id = auth.uid();

  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_all_notifications_read()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_count integer;
BEGIN
  UPDATE public.notifications
  SET is_read = true
  WHERE user_id = auth.uid()
    AND is_read = false;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_policy_attestation(
  p_policy_id uuid,
  p_user_id uuid,
  p_due_at timestamptz DEFAULT NULL,
  p_instructions text DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_policy public.policies%ROWTYPE;
  v_attestation_id uuid;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF NOT public.is_elevated_role() THEN
    RAISE EXCEPTION 'Only elevated roles can request attestations';
  END IF;

  SELECT *
  INTO v_policy
  FROM public.policies
  WHERE id = p_policy_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Policy % not found', p_policy_id;
  END IF;

  IF v_policy.status <> 'approved' THEN
    RAISE EXCEPTION 'Policy % must be approved before requesting attestation', p_policy_id;
  END IF;

  SELECT id
  INTO v_attestation_id
  FROM public.policy_attestations
  WHERE policy_id = p_policy_id
    AND user_id = p_user_id
    AND status = 'pending'
  ORDER BY requested_at DESC
  LIMIT 1;

  IF v_attestation_id IS NOT NULL THEN
    UPDATE public.policy_attestations
    SET
      instructions = p_instructions,
      due_at = p_due_at,
      requested_by = auth.uid(),
      requested_at = now(),
      notes = NULL
    WHERE id = v_attestation_id;
  ELSE
    UPDATE public.policy_attestations
    SET
      status = 'pending',
      instructions = p_instructions,
      due_at = p_due_at,
      requested_by = auth.uid(),
      requested_at = now(),
      acknowledged_at = NULL,
      notes = NULL
    WHERE policy_id = p_policy_id
      AND user_id = p_user_id
      AND status IN ('acknowledged', 'expired')
    RETURNING id INTO v_attestation_id;

    IF v_attestation_id IS NULL THEN
      INSERT INTO public.policy_attestations (
        policy_id,
        user_id,
        requested_by,
        instructions,
        due_at
      )
      VALUES (
        p_policy_id,
        p_user_id,
        auth.uid(),
        p_instructions,
        p_due_at
      )
      RETURNING id INTO v_attestation_id;
    END IF;
  END IF;

  RETURN v_attestation_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.acknowledge_policy_attestation(
  p_attestation_id uuid,
  p_notes text DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_attestation public.policy_attestations%ROWTYPE;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT *
  INTO v_attestation
  FROM public.policy_attestations
  WHERE id = p_attestation_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Attestation % not found', p_attestation_id;
  END IF;

  IF v_attestation.status <> 'pending' THEN
    RAISE EXCEPTION 'Attestation % is already finalized', p_attestation_id;
  END IF;

  IF v_attestation.user_id <> auth.uid() AND NOT public.is_elevated_role() THEN
    RAISE EXCEPTION 'Only the assigned user can acknowledge this attestation';
  END IF;

  UPDATE public.policy_attestations
  SET
    status = 'acknowledged',
    acknowledged_at = now(),
    notes = COALESCE(p_notes, notes)
  WHERE id = p_attestation_id;

  RETURN p_attestation_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_policy_attestation_summary(p_policy_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
AS $$
DECLARE
  v_result jsonb;
BEGIN
  SELECT jsonb_build_object(
    'policy_id', p_policy_id,
    'attestations', COALESCE(
      (
        SELECT jsonb_agg(
          jsonb_build_object(
            'id', pa.id,
            'policy_id', pa.policy_id,
            'user_id', pa.user_id,
            'requested_by', pa.requested_by,
            'status', pa.status,
            'instructions', pa.instructions,
            'notes', pa.notes,
            'due_at', pa.due_at,
            'requested_at', pa.requested_at,
            'acknowledged_at', pa.acknowledged_at,
            'user_name', assigned_profile.full_name,
            'user_email', assigned_profile.email,
            'requested_by_name', requester_profile.full_name
          )
          ORDER BY pa.requested_at DESC
        )
        FROM public.policy_attestations pa
        LEFT JOIN public.profiles assigned_profile
          ON assigned_profile.id = pa.user_id
        LEFT JOIN public.profiles requester_profile
          ON requester_profile.id = pa.requested_by
        WHERE pa.policy_id = p_policy_id
      ),
      '[]'::jsonb
    )
  )
  INTO v_result;

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.notify_policy_approval_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_policy_title text;
  v_message text;
BEGIN
  SELECT title INTO v_policy_title
  FROM public.policies
  WHERE id = COALESCE(NEW.policy_id, OLD.policy_id);

  IF TG_OP = 'INSERT' AND NEW.status = 'pending' THEN
    v_message := format(
      'Policy "%s" is waiting for %s.',
      COALESCE(v_policy_title, NEW.policy_id::text),
      replace(NEW.stage_name, '_', ' ')
    );

    PERFORM public.notify_users_by_role(
      NEW.required_role,
      'policy_approval',
      v_message,
      jsonb_build_object(
        'policy_id', NEW.policy_id,
        'approval_request_id', NEW.id,
        'stage_name', NEW.stage_name,
        'status', NEW.status
      )
    );
  ELSIF TG_OP = 'UPDATE' AND NEW.status IS DISTINCT FROM OLD.status THEN
    IF NEW.status = 'pending' THEN
      v_message := format(
        'Policy "%s" is now ready for your approval at %s.',
        COALESCE(v_policy_title, NEW.policy_id::text),
        replace(NEW.stage_name, '_', ' ')
      );

      PERFORM public.notify_users_by_role(
        NEW.required_role,
        'policy_approval',
        v_message,
        jsonb_build_object(
          'policy_id', NEW.policy_id,
          'approval_request_id', NEW.id,
          'stage_name', NEW.stage_name,
          'status', NEW.status
        )
      );
    END IF;

    IF NEW.status IN ('approved', 'rejected') THEN
      v_message := format(
        'Policy "%s" approval step "%s" was %s.',
        COALESCE(v_policy_title, NEW.policy_id::text),
        replace(NEW.stage_name, '_', ' '),
        NEW.status
      );

      PERFORM public.send_notification(
        NEW.requested_by,
        'policy_approval',
        v_message,
        jsonb_build_object(
          'policy_id', NEW.policy_id,
          'approval_request_id', NEW.id,
          'stage_name', NEW.stage_name,
          'status', NEW.status
        )
      );
    END IF;
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS policy_approval_notifications ON public.policy_approval_requests;
CREATE TRIGGER policy_approval_notifications
AFTER INSERT OR UPDATE ON public.policy_approval_requests
FOR EACH ROW EXECUTE FUNCTION public.notify_policy_approval_change();

CREATE OR REPLACE FUNCTION public.notify_policy_status_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status AND NEW.status = 'approved' THEN
    PERFORM public.send_notification(
      NEW.created_by,
      'policy_approval',
      format('Policy "%s" has been fully approved and is ready for staff acknowledgment.', NEW.title),
      jsonb_build_object(
        'policy_id', NEW.id,
        'status', NEW.status
      )
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS policy_status_notifications ON public.policies;
CREATE TRIGGER policy_status_notifications
AFTER UPDATE ON public.policies
FOR EACH ROW EXECUTE FUNCTION public.notify_policy_status_change();

CREATE OR REPLACE FUNCTION public.notify_policy_attestation_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_policy_title text;
BEGIN
  SELECT title INTO v_policy_title
  FROM public.policies
  WHERE id = COALESCE(NEW.policy_id, OLD.policy_id);

  IF TG_OP = 'INSERT' THEN
    PERFORM public.send_notification(
      NEW.user_id,
      'policy_attestation',
      format('Please acknowledge policy "%s".', COALESCE(v_policy_title, NEW.policy_id::text)),
      jsonb_build_object(
        'policy_id', NEW.policy_id,
        'attestation_id', NEW.id,
        'status', NEW.status
      ),
      NEW.due_at
    );
  ELSIF TG_OP = 'UPDATE' AND NEW.status IS DISTINCT FROM OLD.status AND NEW.status = 'acknowledged' THEN
    PERFORM public.send_notification(
      NEW.requested_by,
      'policy_attestation',
      format('User acknowledgment completed for policy "%s".', COALESCE(v_policy_title, NEW.policy_id::text)),
      jsonb_build_object(
        'policy_id', NEW.policy_id,
        'attestation_id', NEW.id,
        'status', NEW.status,
        'user_id', NEW.user_id
      )
    );
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS policy_attestation_notifications ON public.policy_attestations;
CREATE TRIGGER policy_attestation_notifications
AFTER INSERT OR UPDATE ON public.policy_attestations
FOR EACH ROW EXECUTE FUNCTION public.notify_policy_attestation_change();
